# Hyperparameters
train_epoch: 1000
learning_rate: 1
early_stop: 5

# Model
model: 'vgg19'

# How much to weight the content reconstruction term. 
alpha: 1

# How much to weight the style reconstruction term. 
beta: 500000

# Original colors 
# True = output image will keep the colors of the content image
original_colors: True

# Images to blend:
content_image: './data/luke_images/content/luke_2c.jpeg'
style_image: './data/luke_images/content/portrait_2c.jpeg'

# Generate Image: 
# true = start with generated pink noise || false = start with content image (use this for faster results)
generate_image: False