# Hyperparameters
train_epoch: 2000
learning_rate: 0.2
early_stop: 5

# Model
model: 'vgg19_shifted'

# How much to weight the content reconstruction term. 
alpha: 1000

# How much to weight the style reconstruction term. 
beta: 50000000

gamma: 0.00001

# Images to blend:
content_image: './data/team_headshots/@1xcole_crop.jpg'
style_image: './data/art/art29.jpg'

# Use segmentaion mask (read README.md for instructions)
use_mask: False

# Use LBFGS optimizer instead of Adam (LBFGS takes more time and memory but produces sharper images)
lbfgs : True

# Generate Image: 
# true = start with generated pink noise || false = start with content image (use this for faster results)
generate_image: True

# Show original content image colors on top of generated image
original_colors: False
