# Hyperparameters
train_epoch: 2000
learning_rate: 0.2
early_stop: 5

# Model
model: 'vgg19'

# How much to weight the content reconstruction term. 
alpha: 10

# How much to weight the style reconstruction term. 
beta: 500000

gamma: 0.00001
# gamma: 0

# Images to blend:
# content_image: './data/luke_images/content/building_11c.jpeg'
content_image: './data/seg_test/luke_2c_small.jpeg'
style_image: './data/seg_test/art7.jpg'

# Use segmentaion mask (read README.md for instructions)
use_mask: True

# Use LBFGS optimizer instead of Adam (LBFGS takes more time and memory but produces sharper images)
lbfgs : False

# Generate Image: 
# true = start with generated pink noise || false = start with content image (use this for faster results)
generate_image: False

# Show original content image colors on top of generated image
original_colors: True