# Hyperparameters
train_epoch: 5000
learning_rate: 0.2
early_stop: 5

# Model
model: 'vgg19'

# How much to weight the content reconstruction term. 
alpha: 10

# How much to weight the style reconstruction term. 
beta: 500000

gamma: 0.0001
# gamma: 0

# Images to blend:
# content_image: './data/luke_images/content/building_11c.jpeg'
content_image: './data/seg_test/landscape_8s.jpg'
style_image: './data/seg_test/landscape9.jpg'

use_mask: False

# Generate Image: 
# true = start with generated pink noise || false = start with content image (use this for faster results)
generate_image: False

lbfgs: False
original_colors: False